### ISSUE TITLE
Add readme with description?

### ISSUE THREAD

**Issue by Darthagnon** [Studumb/InvincibleCheat#1]
On the Spore Discord, this mod is described as:

> Add a new cheat with the syntax: "invincible" which make spaceship immune to damage.
> -This cheat won't give Joker badge or disable achievement.

Would be nice to have in a Readme

**Comment by Studumb** [comment]
> On the Spore Discord, this mod is described as:
> 
> > Add a new cheat with the syntax: "invincible" which make spaceship immune to damage.
> > -This cheat won't give Joker badge or disable achievement.
> 
> Would be nice to have in a Readme

Thanks for reminding, I totally forgot about it
